apiVersion: v1
kind: Namespace
metadata:
  name: flussonic
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
  namespace: flussonic
handler: nvidia
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streamer-presets
  namespace: flussonic
data:
  edit_auth: |
    edit_auth admin admin;
  ports: |
    http 8888;
  stream: |
    stream fake {
      input fake://;
      transcoder deviceid=0 external=false hw=nvenc vb=300k vcodec=h264 size=-1x1080 deinterlace=true deinterlace_rate=frame ab=128k acodec=aac;
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nvenc-pod
  namespace: flussonic
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  containers:
    - name: flussonic
      image: flussonic/flussonic:latest
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 8888
        hostPort: 8888
      env:
      - name: LICENSE_KEY
        value: PASTE_YOUR_LICENSE_KEY_HERE
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: all
      - name: DP_DISABLE_HEALTHCHECKS
        value: xids
      volumeMounts:
      - name: config-templates
        mountPath: /etc/flussonic/flussonic.conf.d
  volumes:
  - name: config-templates
    configMap:
      name: streamer-presets
      items:
      - key: ports
        path: ports.conf
      - key: stream
        path: stream.conf
      - key: edit_auth
        path: edit_auth.conf
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule